

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: consumer

server:
  port: 8081

x:
  invoice: x.invoice
  invoice-cancel: x.invoice.cancel

q:
  invoice: q.invoice
  invoice-cancel: x.invoice.cancel
