

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#    listener:
#      simple:
#        prefetch: 1
  application:
    name: consumer

server:
  port: 8081

x:
  dummy: x.dummy

q:
  dummy: q.dummy