
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
  application:
    name: producer

server:
  port: 8080

x:
  invoice: x.invoice
  invoice-cancel: x.invoice.cancel

q:
  invoice: q.invoice
  invoice-cancel: x.invoice.cancel
