
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
  application:
    name: producer

server:
  port: 8080

x:
  single: x.single

q:
  single: q.single
